In [2]:
import numpy as np

In [11]:
data_path = 'data\ML25M\BPR_cv\BPR_ivec_4.npy'
item = np.load(data_path)
zero_embeddings = np.all(item == 0, axis=1)
if np.any(zero_embeddings):
    print(np.where(zero_embeddings == True))
    print(f"0으로만 채워진 임베딩 벡터가 {np.sum(zero_embeddings)}개 있습니다.")
else:
    print("0으로만 채워진 임베딩 벡터가 없습니다.")


data_path = 'data/ML25M/mv-tag-emb.npy'
tag = np.load(data_path)
zero_embeddings = np.all(tag == 0, axis=1)

if np.any(zero_embeddings):
    print(zero_embeddings.index(True))
    print(f"0으로만 채워진 임베딩 벡터가 {np.sum(zero_embeddings)}개 있습니다.")
else:
    print("0으로만 채워진 임베딩 벡터가 없습니다.")

(array([   14,    22,    23, ..., 13806, 13808, 13810], dtype=int64),)
0으로만 채워진 임베딩 벡터가 2764개 있습니다.
0으로만 채워진 임베딩 벡터가 없습니다.


In [15]:
data_path = 'data\ML25M\BPR_cv\BPR_ivec_4.npy'
data = np.load(data_path)
zero_embeddings = np.all(data == 0, axis=1)
if np.any(zero_embeddings):
    print(f"0으로만 채워진 임베딩 벡터가 {np.sum(zero_embeddings)}개 있습니다.")
else:
    print("0으로만 채워진 임베딩 벡터가 없습니다.")

data[zero_embeddings].shape

0으로만 채워진 임베딩 벡터가 2764개 있습니다.


(2764, 128)

In [5]:
import torch
num_classes = 10
torch.randint(0, num_classes, (8,))

tensor([3, 6, 9, 3, 0, 8, 7, 3])

In [10]:
data_path = 'data\ML25M\BPR_cv\BPR_ivec_0.npy'
item = np.load(data_path)
item

array([[-0.06682408,  0.34707013, -0.3154866 , ...,  0.38255832,
        -0.07169646,  0.3006588 ],
       [-0.02712425,  0.24701644, -0.22818725, ...,  0.18251069,
        -0.07793371,  0.27911147],
       [ 0.08703583,  0.13494784, -0.38311225, ...,  0.10247398,
         0.15477848,  0.26990607],
       ...,
       [-0.05939461, -0.41062385,  0.45251924, ...,  0.30205137,
         0.06413885, -0.17306776],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-0.07361117, -0.38024035,  0.36830074, ...,  0.12259404,
         0.08729994, -0.14923485]], dtype=float32)

In [19]:
data_path = 'data\ML25M\BPR_cv/top_k_nn_item_index_0.npy'
data = np.load(data_path)
data

array([[ 4407, 10285,  2094, ..., 10580,  9385, 12384],
       [ 1777,  3122,   148, ...,  6619,  1804,  1767],
       [  411,  6352,  4726, ...,  1608,  2507,  4538],
       ...,
       [13573, 13460, 13515, ..., 13465, 13778, 13476],
       [13051, 13811, 13179, ...,  8158,  8931, 13414],
       [13749, 13556, 13615, ..., 13725, 13770, 13685]])

In [12]:
data_path = 'data\ML25M\BPR_cv/top_k_nn_item_sim_0.npy'
data = np.load(data_path)
data

array([[0.92558926, 0.8924986 , 0.8855711 , ..., 0.8003852 , 0.79656696,
        0.7956278 ],
       [0.8053264 , 0.76107544, 0.74586433, ..., 0.6705703 , 0.66925853,
        0.6677883 ],
       [0.93699753, 0.87973094, 0.8765104 , ..., 0.8338019 , 0.83178204,
        0.8297069 ],
       ...,
       [0.7442296 , 0.73323685, 0.7276896 , ..., 0.7041369 , 0.7025748 ,
        0.6957799 ],
       [0.7459877 , 0.7294137 , 0.68902755, ..., 0.64137644, 0.6393935 ,
        0.63892084],
       [0.7453746 , 0.74030876, 0.7391306 , ..., 0.7047485 , 0.6827469 ,
        0.6795477 ]], dtype=float32)

In [49]:
import pandas as pd

val_path = 'data\ML25M\BPR_cv\BPR_val_0.tsv'
bpr_val = pd.read_csv(val_path, sep='\t', header=0)

cold_movies_vali_path = 'data\ML25M\BPR_cv\cold_movies_rating_vali_0.tsv'
cold_movies_test_path = 'data\ML25M\BPR_cv\cold_movies_rating_test_0.tsv'
# Reload the cold_movies_vali_0.tsv file without the header
vali_df = pd.read_csv(cold_movies_vali_path, sep='\t', header=0)
test_df = pd.read_csv(cold_movies_test_path, sep='\t', header=0)

# Check if all movie IDs in the filtered BPR_val_0.tsv exist in the cold_movies_vali_0.tsv
merged_df = pd.concat([vali_df, test_df])
print(merged_df.head())

# Sorting by user id
sorted_df = merged_df.sort_values(by='uid')
sorted_df.reset_index(drop=True, inplace=True)

sorted_df.head()

   uid   mid  rating
0    2  9844     4.0
1    2  9925     4.5
2    2  9931     4.0
3    2  9956     4.0
4    2  9966     4.0


uid   mid  rating
0    0   618     5.0
1    0  6697     3.5
2    0  6664     4.5
3    0  6396     3.5
4    0  6330     4.5

In [50]:
sorted_df.to_csv('data\ML25M\BPR_cv\cold_movies_rating_all_0.tsv', sep='\t', index=False)

In [33]:
cold_movie_ids = cold_movies_vali_df['mid'].astype(int)
cold_movie_ids

0       9744
1       9750
2       9761
3       9762
4       9771
       ...  
824    13783
825    13784
826    13785
827    13809
828    13814
Name: mid, Length: 829, dtype: int32

In [39]:
bpr_movie_ids.unique().shape

(10979,)