In [2]:
import numpy as np

In [21]:
data_path = 'data\ML25M\BPR_cv\BPR_ivec_4.npy'
item = np.load(data_path)
zero_embeddings = np.all(item == 0, axis=1)
if np.any(zero_embeddings):
    print(f"0으로만 채워진 임베딩 벡터가 {np.sum(zero_embeddings)}개 있습니다.")
else:
    print("0으로만 채워진 임베딩 벡터가 없습니다.")


data_path = 'data/ML25M/mv-tag-emb.npy'
tag = np.load(data_path)
zero_embeddings = np.all(tag == 0, axis=1)
if np.any(zero_embeddings):
    print(f"0으로만 채워진 임베딩 벡터가 {np.sum(zero_embeddings)}개 있습니다.")
else:
    print("0으로만 채워진 임베딩 벡터가 없습니다.")
                                

item_shape_consistent = len(set([row.shape for row in item])) == 1
tag_shape_consistent = len(set([row.shape for row in tag])) == 1

if item_shape_consistent and tag_shape_consistent:
    print("item_embeddings와 tag_embeddings의 모든 행이 같은 크기를 가지고 있습니다.")
else:
    print("행 크기가 일치하지 않습니다.")

0으로만 채워진 임베딩 벡터가 2764개 있습니다.
0으로만 채워진 임베딩 벡터가 없습니다.
item_embeddings와 tag_embeddings의 모든 행이 같은 크기를 가지고 있습니다.


In [18]:
data_path = 'data\ML25M\BPR_cv\BPR_ivec_4.npy'
data = np.load(data_path)
zero_embeddings = np.all(data == 0, axis=1)
if np.any(zero_embeddings):
    print(f"0으로만 채워진 임베딩 벡터가 {np.sum(zero_embeddings)}개 있습니다.")
else:
    print("0으로만 채워진 임베딩 벡터가 없습니다.")

0으로만 채워진 임베딩 벡터가 2764개 있습니다.


In [5]:
import torch
num_classes = 10
torch.randint(0, num_classes, (8,))

tensor([3, 6, 9, 3, 0, 8, 7, 3])

In [10]:
data_path = 'data\ML25M\BPR_cv\BPR_ivec_0.npy'
item = np.load(data_path)
item

array([[-0.06682408,  0.34707013, -0.3154866 , ...,  0.38255832,
        -0.07169646,  0.3006588 ],
       [-0.02712425,  0.24701644, -0.22818725, ...,  0.18251069,
        -0.07793371,  0.27911147],
       [ 0.08703583,  0.13494784, -0.38311225, ...,  0.10247398,
         0.15477848,  0.26990607],
       ...,
       [-0.05939461, -0.41062385,  0.45251924, ...,  0.30205137,
         0.06413885, -0.17306776],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-0.07361117, -0.38024035,  0.36830074, ...,  0.12259404,
         0.08729994, -0.14923485]], dtype=float32)

In [8]:
data_path = 'data\ML25M\BPR_cv/top_k_nn_item_index_0.npy'
data = np.load(data_path)
data

array([[ 4407, 10285,  2094, ..., 10580,  9385, 12384],
       [ 1777,  3122,   148, ...,  6619,  1804,  1767],
       [  411,  6352,  4726, ...,  1608,  2507,  4538],
       ...,
       [13573, 13460, 13515, ..., 13465, 13778, 13476],
       [13051, 13811, 13179, ...,  8158,  8931, 13414],
       [13749, 13556, 13615, ..., 13725, 13770, 13685]])

In [12]:
data_path = 'data\ML25M\BPR_cv/top_k_nn_item_sim_0.npy'
data = np.load(data_path)
data

array([[0.92558926, 0.8924986 , 0.8855711 , ..., 0.8003852 , 0.79656696,
        0.7956278 ],
       [0.8053264 , 0.76107544, 0.74586433, ..., 0.6705703 , 0.66925853,
        0.6677883 ],
       [0.93699753, 0.87973094, 0.8765104 , ..., 0.8338019 , 0.83178204,
        0.8297069 ],
       ...,
       [0.7442296 , 0.73323685, 0.7276896 , ..., 0.7041369 , 0.7025748 ,
        0.6957799 ],
       [0.7459877 , 0.7294137 , 0.68902755, ..., 0.64137644, 0.6393935 ,
        0.63892084],
       [0.7453746 , 0.74030876, 0.7391306 , ..., 0.7047485 , 0.6827469 ,
        0.6795477 ]], dtype=float32)