In [65]:
import numpy as np
import pandas as pd

In [11]:
data_path = 'data\ML25M\BPR_cv\BPR_ivec_4.npy'
item = np.load(data_path)
zero_embeddings = np.all(item == 0, axis=1)
if np.any(zero_embeddings):
    print(np.where(zero_embeddings == True))
    print(f"0으로만 채워진 임베딩 벡터가 {np.sum(zero_embeddings)}개 있습니다.")
else:
    print("0으로만 채워진 임베딩 벡터가 없습니다.")


data_path = 'data/ML25M/mv-tag-emb.npy'
tag = np.load(data_path)
zero_embeddings = np.all(tag == 0, axis=1)

if np.any(zero_embeddings):
    print(zero_embeddings.index(True))
    print(f"0으로만 채워진 임베딩 벡터가 {np.sum(zero_embeddings)}개 있습니다.")
else:
    print("0으로만 채워진 임베딩 벡터가 없습니다.")

(array([   14,    22,    23, ..., 13806, 13808, 13810], dtype=int64),)
0으로만 채워진 임베딩 벡터가 2764개 있습니다.
0으로만 채워진 임베딩 벡터가 없습니다.


In [62]:
data_path = 'data\ML25M\BPR_cv\BPR_ivec_0.npy'
items = np.load(data_path)
min_val = np.inf
max_val = -np.inf
for item in items:
    if min_val > min(item):
        min_val = min(item)

    if max_val < max(item):
        max_val = max(item)

In [66]:
import pandas as pd

train_path = 'data\ML25M\BPR_cv\BPR_tr_0.tsv'
vali_path = 'data\ML25M\BPR_cv\BPR_val_0.tsv'
test_path = 'data\ML25M\BPR_cv\BPR_test_0.tsv'
# Reload the cold_movies_vali_0.tsv file without the header
train_df = pd.read_csv(train_path, sep='\t', header=0)
vali_df = pd.read_csv(vali_path, sep='\t', header=0)
test_df = pd.read_csv(test_path, sep='\t', header=0)

# Check if all movie IDs in the filtered BPR_val_0.tsv exist in the cold_movies_vali_0.tsv
merged_df = pd.concat([train_df, vali_df, test_df])
print(merged_df.head())

# Sorting by user id
sorted_df = merged_df.sort_values(by='uid')
sorted_df.reset_index(drop=True, inplace=True)

sorted_df.head()

   uid   mid  rating
0    0   292     3.5
1    0   293     5.0
2    0   985     4.0
3    0  1054     3.5
4    0  1093     3.5


uid   mid  rating
0    0   292     3.5
1    0  6808     4.0
2    0  6839     3.5
3    0  7039     4.0
4    0  7097     3.0

In [67]:
sorted_df.to_csv('data\ML25M\BPR_cv\BPR_all_0.tsv', sep='\t', index=False)

In [68]:
import pandas as pd

nonzero_path = 'data\ML25M\BPR_cv\BPR_all_0.tsv'
zero_path = 'data\ML25M\BPR_cv\cold_movies_rating_all_0.tsv'

# Reload the cold_movies_vali_0.tsv file without the header
df1 = pd.read_csv(nonzero_path, sep='\t', header=0)
df2 = pd.read_csv(zero_path, sep='\t', header=0)

# Check if all movie IDs in the filtered BPR_val_0.tsv exist in the cold_movies_vali_0.tsv
merged_df = pd.concat([df1, df2])
print(merged_df.head())

# Sorting by user id
sorted_df = merged_df.sort_values(by='uid')
sorted_df.reset_index(drop=True, inplace=True)

sorted_df.head()

   uid   mid  rating
0    0   292     3.5
1    0  6808     4.0
2    0  6839     3.5
3    0  7039     4.0
4    0  7097     3.0


uid   mid  rating
0    0   292     3.5
1    0   985     4.0
2    0   293     5.0
3    0  6661     3.0
4    0  1134     3.5

In [69]:
sorted_df.to_csv('data\ML25M\BPR_cv\BPR_all_cold_all_0.tsv', sep='\t', index=False)

In [21]:
data_path = 'data\ML25M\BPR_cv\BPR_uvec_0.npy'
user = np.load(data_path)
len(user_embeddings)

(162540, 128)

In [10]:
ratings = pd.read_csv('data\ML25M\BPR_cv\cold_movies_rating_all_0.tsv', sep='\t')
uids = set(ratings['uid'].unique())

null_list = [idx for idx in range(len(user_embeddings)) if i not in uids]

In [11]:
len(null_list)

950

In [12]:
len(uids)

161590

In [77]:
user_embeddings = np.arange(0,24).reshape((3,8))
user_embeddings

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [108]:
item_embeddings = [np.arange(0, 5)] * 8 
item_embeddings = np.array(item_embeddings).reshape((5,8))
item_embeddings

array([[0, 1, 2, 3, 4, 0, 1, 2],
       [3, 4, 0, 1, 2, 3, 4, 0],
       [1, 2, 3, 4, 0, 1, 2, 3],
       [4, 0, 1, 2, 3, 4, 0, 1],
       [2, 3, 4, 0, 1, 2, 3, 4]])

In [109]:
scores = np.dot(user_embeddings, item_embeddings.T)
scores

array([[ 50,  54,  58,  47,  71],
       [154, 190, 186, 167, 223],
       [258, 326, 314, 287, 375]])

In [110]:
item_indices = np.argsort(scores, axis=1)[:, ::-1][:, :3].tolist()
item_indices

[[4, 2, 1], [4, 1, 2], [4, 1, 2]]

In [111]:
user_indices = np.arange(user_embeddings.shape[0])[:, None]
user_indices

array([[0],
       [1],
       [2]])

In [112]:
top_k_scores = scores[user_indices, item_indices]
top_k_scores

array([[ 71,  58,  54],
       [223, 190, 186],
       [375, 326, 314]])

In [83]:
1 + 4 + 9 + 16 + 25 + 36 + 49
64 + 81 + 100 + 121 + 144 + 169 + 196 + 225

1100

In [84]:
9 + 20 + 33 + 48 + 65 + 84 + 105

364